name: CI

on:
  push:
  pull_request:

permissions:
  contents: read
  packages: write

jobs:

  lint-and-test:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Lint
        run: |
          ruff check .

      - name: Tests
        run: |
          pytest -v


  secret-scan:
    runs-on: ubuntu-24.04
    needs: lint-and-test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Gitleaks scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  sast:
    runs-on: ubuntu-24.04
    needs: lint-and-test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Semgrep
        run: |
          python -m pip install semgrep

      - name: Run Semgrep
        id: semgrep
        continue-on-error: true
        run: |
          semgrep scan \
            --config p/python \
            --sarif \
            --output semgrep.sarif \
            .

      - name: Upload Semgrep report
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: semgrep.sarif

      - name: Apply Semgrep Security Gate
        if: steps.semgrep.outcome == 'failure'
        run: exit 1


  dependency-scan:
    runs-on: ubuntu-24.04
    needs: lint-and-test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Trivy dependency scan
        id: trivy_deps
        continue-on-error: true
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: fs
          scan-ref: .
          scanners: vuln
          severity: CRITICAL,HIGH
          format: json
          output: trivy-dependencies.json
          exit-code: '1'
          ignore-unfixed: false

      - name: Upload dependency report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-dependencies-report
          path: trivy-dependencies.json

      - name: Apply dependency Security Gate
        if: steps.trivy_deps.outcome == 'failure'
        run: exit 1


  iac-scan:
    runs-on: ubuntu-24.04
    needs: lint-and-test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Trivy IaC scan
        id: trivy_iac
        continue-on-error: true
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: config
          scan-ref: .
          severity: CRITICAL,HIGH
          format: json
          output: trivy-iac.json
          exit-code: '1'

      - name: Upload IaC report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-iac-report
          path: trivy-iac.json

      - name: Apply IaC Security Gate
        if: steps.trivy_iac.outcome == 'failure'
        run: exit 1

  policy-as-code:
    runs-on: ubuntu-24.04
    needs: lint-and-test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Conftest
        run: |
          LATEST_VERSION=$(curl -s https://api.github.com/repos/open-policy-agent/conftest/releases/latest \
            | grep '"tag_name":' \
            | sed -E 's/.*"([^"]+)".*/\1/' \
            | cut -c 2-)

          curl -L \
            "https://github.com/open-policy-agent/conftest/releases/download/v${LATEST_VERSION}/conftest_${LATEST_VERSION}_Linux_x86_64.tar.gz" \
            -o conftest.tar.gz

          tar xzf conftest.tar.gz
          sudo mv conftest /usr/local/bin/

          conftest --version

      - name: Run Policy as Code checks
        run: |
          conftest test \
            --policy policy/ \
            k3s/deployment.yaml



  docker-build-scan-push:
    runs-on: ubuntu-24.04

    needs:
      - secret-scan
      - sast
      - dependency-scan
      - iac-scan
      - policy-as-code

    if: always() && github.event_name == 'push'

    env:
      IMAGE_NAME: ghcr.io/salim-nejdi/devsecops-app:${{ github.sha }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build \
            -t "${IMAGE_NAME}" \
            .

      - name: Trivy image scan
        id: trivy_image
        continue-on-error: true
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: image
          image-ref: ${{ env.IMAGE_NAME }}
          severity: CRITICAL,HIGH
          format: json
          output: trivy-image.json
          exit-code: '1'
          ignore-unfixed: false

      - name: Upload image report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-image-report
          path: trivy-image.json

      - name: Apply image Security Gate
        if: steps.trivy_image.outcome == 'failure'
        run: exit 1

      - name: Login to GHCR
        if: |
          success() &&
          needs.secret-scan.result == 'success' &&
          needs.sast.result == 'success' &&
          needs.dependency-scan.result == 'success' &&
          needs.iac-scan.result == 'success'
          needs.policy-as-code.result == 'success'
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | \
          docker login ghcr.io \
            -u "${{ github.actor }}" \
            --password-stdin

      - name: Push image to GHCR
        if: |
          success() &&
          needs.secret-scan.result == 'success' &&
          needs.sast.result == 'success' &&
          needs.dependency-scan.result == 'success' &&
          needs.iac-scan.result == 'success'
          needs.policy-as-code.result == 'success'
        run: |
          docker push "${IMAGE_NAME}"
